name: flutter_tweet_storm
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  amplify_analytics_pinpoint:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/analytics/amplify_analytics_pinpoint
  amplify_api:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/api/amplify_api
  amplify_auth_cognito:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/auth/amplify_auth_cognito
  amplify_authenticator:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/amplify_authenticator
  amplify_flutter:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/amplify/amplify_flutter
  amplify_storage_s3:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/storage/amplify_storage_s3
  cached_network_image: ^3.2.2
  faker: ^2.0.0
  file_picker: ^5.2.2
  flutter:
    sdk: flutter
  stream_transform: ^2.1.0
  timeago: ^3.3.0

dependency_overrides:
  amplify_analytics_pinpoint:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/analytics/amplify_analytics_pinpoint
  amplify_analytics_pinpoint_dart:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/analytics/amplify_analytics_pinpoint_dart
  amplify_api:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/api/amplify_api
  amplify_api_android:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/api/amplify_api_android
  amplify_api_ios:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/api/amplify_api_ios
  amplify_auth_cognito:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/auth/amplify_auth_cognito
  amplify_auth_cognito_android:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/auth/amplify_auth_cognito_android
  amplify_auth_cognito_dart:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/auth/amplify_auth_cognito_dart
  amplify_auth_cognito_ios:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/auth/amplify_auth_cognito_ios
  amplify_core:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/amplify_core
  amplify_flutter:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/amplify/amplify_flutter
  amplify_flutter_android:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/amplify/amplify_flutter_android
  amplify_flutter_ios:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/amplify/amplify_flutter_ios
  amplify_secure_storage:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/secure_storage/amplify_secure_storage
  amplify_secure_storage_dart:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/secure_storage/amplify_secure_storage_dart
  amplify_storage_s3:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/storage/amplify_storage_s3
  amplify_storage_s3_dart:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/storage/amplify_storage_s3_dart
  aws_common:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/aws_common
  aws_signature_v4:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/aws_signature_v4
  smithy:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/smithy/smithy
  smithy_aws:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/smithy/smithy_aws
  worker_bee:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/worker_bee/worker_bee

dev_dependencies:
  amplify_lints: ^2.0.0
  flutter_native_splash: ^2.2.7
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.0.4

# To generate, run:
# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: '#ffffff'
  image: assets/logo.png
  android: false
  ios: false
  web: true

# To generate, run:
# flutter pub run icons_launcher:create
icons_launcher:
  image_path: assets/logo.png
  platforms:
    web:
      enable: true
    macos:
      enable: true

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Amazon Ember
      fonts:
      - asset: fonts/AmazonEmber_Th.ttf
        weight: 100
      - asset: fonts/AmazonEmber_ThIt.ttf
        weight: 100
        style: italic
      - asset: fonts/AmazonEmber_Lt.ttf
        weight: 300
      - asset: fonts/AmazonEmber_LtIt.ttf
        weight: 300
        style: italic
      - asset: fonts/AmazonEmber_Rg.ttf
      - asset: fonts/AmazonEmber_RgIt.ttf
        style: italic
      - asset: fonts/Amazon-Ember-Medium.ttf
        weight: 500
      - asset: fonts/Amazon-Ember-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: fonts/AmazonEmber_Bd.ttf
        weight: 700
      - asset: fonts/AmazonEmber_BdIt.ttf
        weight: 700
        style: italic
      - asset: fonts/AmazonEmber_He.ttf
        weight: 900
      - asset: fonts/AmazonEmber_HeIt.ttf
        weight: 900
        style: italic
